name: ShellCheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: |
          shellcheck -x install.sh package/manage.sh package/on-boot.sh build/package.sh
          shellcheck -x -e SC2154 package/common.sh
